using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace QuicMoc.Sources;

internal static class AnyType
{
    public static IncrementalGeneratorPostInitializationContext AddAnyTypeSource(
        this IncrementalGeneratorPostInitializationContext context
    )
    {
        context.AddSource(
            "AnyType.g.cs",
            SourceText.From(
                $"""
                // <auto-generated />
                #nullable enable

                namespace {Constants.Namespace};

                public readonly record struct AnyType;
                
                """,
                Encoding.UTF8
            )
        );
        return context;
    }
}
