using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace QuicMoc.Sources;

internal static class Arg
{
    public static IncrementalGeneratorPostInitializationContext AddArgSource(
        this IncrementalGeneratorPostInitializationContext context
    )
    {
        context.AddSource(
            "Arg.g.cs",
            SourceText.From(
                $$"""
                // <auto-generated />
                namespace {{Constants.Namespace}};

                public readonly record struct Arg<T>
                {
                    private readonly Func<T, bool> _match;
                    
                    private Arg(Func<T, bool> match)
                    {
                        _match = match;
                    }

                    public static Arg<T> Any() => new Arg<T>(_ => true);
                    
                    internal bool Matches(T other) => _match(other);
                    
                    public static Arg<T> Exactly(T value) => new Arg<T>(x => x.Equals(value));
                    
                    public override int GetHashCode() => 0;
                    
                    public static Arg<T> Is(Func<T, bool> match) => new Arg<T>(match);
                    
                    public static implicit operator Arg<T>(T value) => Arg<T>.Exactly(value);
                }
                
                """,
                Encoding.UTF8
            )
        );
        return context;
    }
}
