using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace QuicMoc.Sources;

internal static class Mock
{
    public const string ClassName = "Mock";

    public static IncrementalGeneratorPostInitializationContext AddMockSource(
        this IncrementalGeneratorPostInitializationContext context
    )
    {
        context.AddSource(
            $"{ClassName}.g.cs",
            SourceText.From(
                $"""
                // <auto-generated />
                namespace {Constants.Namespace};

                public sealed class {ClassName}<T>;
                
                """,
                Encoding.UTF8
            )
        );
        return context;
    }
}
